### PR TITLE
Target net60

### PR DESCRIPTION
**Pull request by dustinsoftware**

### CODE REVIEW

**Comment by hvanbakel** [comment]
@dustinsoftware thank you for the pr, but what does this get you since it already targets net standard? Just curious

**Comment by hvanbakel** [comment]
Are you looking for the nupkgs in particular? I probably need to update keys if you are.

**Comment by dustinsoftware** [comment]
Yeah dotnet tool install will pull from nuget so those need an update..

**Comment by hvanbakel** [comment]
I'll see if I can get those back publishing over the weekend

**Pull request merged**
