### PR TITLE
Import Microsoft.DotNet.Cli.CommandLine sources

### LINKED ISSUE #221: Unable to resolve dependency 'Microsoft.DotNet.Cli.CommandLine'
When attempting to install this nuget package (version 3.0.6) I get this error:

Unable to resolve dependency 'Microsoft.DotNet.Cli.CommandLine'

Sure enough this package doesn't exist in Nuget

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
dotnet team is reluctant to publish NuGet package to non-internal feed and MSBuild team is too busy with implementing new features rather than perfecting already existing ones.

Fixes #221.

### CODE REVIEW

**Comment by mungojam** [comment]
What do we use the package for? It seems odd that we need it when other similar global tools presumably don't

**Comment by andrew-boyarshin** [comment]
@mungojam it's a command-line parser used by .NET Core CLI.

**Comment by hvanbakel** [comment]
I assume this is a 1:1 copy of the source, right? Looks good to me. Thanks @andrew-boyarshin

**Comment by andrew-boyarshin** [comment]
Yes, it is, no modifications to the source, all other files (csproj, ps1 and alike) removed. Merging.

**Comment by andrew-boyarshin** [comment]
A new release would be nice, @hvanbakel.

**Pull request merged**
