### PR TITLE
Create appveyor.yml

### PR DESCRIPTION
**Pull request by casz**
Just initial AppVeyor

Here is some suggestion for GitHub deploy:
https://github.com/search?utf8=%E2%9C%93&q=filename%3Aappveyor+dotnet+deploy+github&type=

should be pretty easy to adapt.

### CODE REVIEW

**Comment by casz** [comment]
test is currently failing actually 👍 https://ci.appveyor.com/project/casz/csprojtovs2017/build/1.4.2

Got xml exception reading packages.config: Data at the root level is invalid. Line 1, position 1.
File C:\projects\csprojtovs2017\Project2015To2017Tests\bin\Debug\netcoreapp1.1\TestFiles\readonly.testcsproj is readonly, please make the file writable first (checkout from source control?).
File C:\projects\csprojtovs2017\Project2015To2017Tests\bin\Debug\netcoreapp1.1\TestFiles\nonexistent.testcsproj could not be found.

**Comment by casz** [comment]
You could properly set it to only build on Master branch to avoid bumping build number.

**Comment by casz** [comment]
So we can have it build both debug and release or just release, I will leave that up to you 👍 
For whatever reason, it's not picking up the tests 👎

**Comment by hvanbakel** [comment]
I believe that is a limitation of AppVeyor, I had it manually run dotnet
test :)

**Comment by casz** [comment]
Well, reading over it they should support dotnet test
https://github.com/appveyor/ci/issues/1404#issuecomment-339427867

**Comment by hvanbakel** [comment]
yes, but I have that in my build defintion as a separate step. So it
basically runs a command line tool which happens to be running tests

**Pull request merged**
