### PR TITLE
Fix #50: Crash when project contains wild card includes

### LINKED ISSUE #50: Crash when project contains wildcard includes
when the project file contains e.g.  `<Compile Include="*.cs" />`, conversion crashes with exception "Illegal characters in path".

### PR DESCRIPTION
**Pull request by tom-englert**
Fix #51 and #52

### CODE REVIEW

**Comment by hvanbakel** [comment]
There seems to be a failing test, can you fix that or do you want me to do it in the merge?

**Comment by tom-englert** [comment]
I'll have a look, seems this topic has some side effects

**Comment by hvanbakel** [comment]
Thanks!

**Comment by tom-englert** [comment]
😄

**Pull request merged**
