### PR TITLE
AppVeyor improvements

### PR DESCRIPTION
**Pull request by andrew-boyarshin**
* Rewrite AppVeyor configuration related to actual build & test
* Improve CI performance
* Use SourceLink
* Simplify project files
* Don't generate nupkg during local development

Note: I'd like to fix Project2015To2017Tests namespaces before 4.0 (API breaking changes) release.

### CODE REVIEW

**Comment by hvanbakel** [comment]
You can rename anything in the test project, we don’t package that up so you can’t break anyone. Same for the console applications.

**Comment by andrew-boyarshin** [comment]
No, I meant doing that not in this PR but before 4.0.

**Comment by andrew-boyarshin** [comment]
And there is one more thing to do before 4.0 - move VS15-specific diagnostics to Migrate2017 project.

**Comment by hvanbakel** [comment]
`SourceLink` will allow debugging I assume? So VS can download pdbs when they’re missing?

**Comment by andrew-boyarshin** [comment]
Not just PDBs, but entire and precise source code related to commit from which NuGet was built.

**Pull request merged**
